---
- name: Install
  hosts: all

  vars:
    pgadmin_password: "changeme"
    pgadmin_username: "coetzeer@gmail.com"
    pgadmin_db_username: pgadmin
    pgadmin_db_password: pgadmin
    pgadmin_install_dir: "/usr/local/pgadmin4/lib/python2.7/site-packages/pgadmin4"

  tasks:
    - name: "Install packages from pkg"
      pkgng:
        name: "{{item}}"
        state: present
      with_items:
      - openjdk8
      - bash
      - rinetd

    - name: Download hub
      get_url:
        url: https://download-cf.jetbrains.com/hub/hub-2018.2.9635.zip
        dest: /usr/local/hub-2018.2.9635.zip
        checksum: sha256:81f065af79802992ab74df5c3af0cba81f678671504b61c1e1fd4aa53341142b

    - name: Unarchive hub
      shell: "unzip hub-2018.2.9635.zip"
      args:
        chdir: /usr/local
        creates: /usr/local/hub-2018.2.9635

    - name: Enable the rinetd service
      shell: "sysrc rinetd_enable=YES"

    - lineinfile:
        path: /usr/local/etc/rinetd.conf
        regexp: '.*8080$'
        line: "{{ansible_default_ipv4.address}} 80 {{ansible_default_ipv4.address}} 8080"
        create: True

    - lineinfile:
        path: /usr/local/etc/rinetd.conf
        line: "logfile /var/log/rinetd.log"

    - lineinfile:
        path: /usr/local/etc/rinetd.conf
        line: "logcommon"

    - name: Start the rinetd daemon
      service:
        name: rinetd
        state: started
        enabled: yes

    - template:
        src: service.j2
        dest: /usr/local/etc/rc.d/hub
        owner: root
        group: wheel
        mode: "u=rwx,g=r,o=r"

    - name: Enable the hub service
      shell: "sysrc hub_enable=YES"

    - name: Start the hub daemon
      service:
        name: hub
        state: started
        enabled: yes
